# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven CI with Rest Assured

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and run Rest Assured Tests with Maven
      if: always()
      run: mvn test
      continue-on-error: true
      
    #generate Allure reports
    # - name: Generate Allure Reports
    #   run: |
    #     mvn allure: serve


    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
       ref: gh-pages
       path: gh-pages


    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

    # Archive results
    # - name: Archive REST-Assured Allure test report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: REST-assured-results
    #     path: target/site/allure-maven

    # - name: Upload-allure-report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Rest-assured-results
    #     path: target/site/allure-maven
#  With these adjustments, your workflow should generate Allure reports correctly and upload them as artifacts, making them available for further inspection or sharing.







# Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
